$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Tune hyperparameters using Image Classification component

jobs:
  train:
    type: command
    component: ../../components/image_classification/spec.yaml
    compute: azureml:gpu-cluster-nc6s
    inputs:
      training_data:
        type: mltable
        path: azureml://datastores/workspaceblobstore/paths/vision-classification/train/
      validation_data:
        type: mltable
        path: azureml://datastores/workspaceblobstore/paths/vision-classification/valid/
      model_name: resnet18
      learning_rate: 0.01
      number_of_epochs: 15
      training_crop_size: 150
    outputs:
      model:
        type: mlflow_model
